app/question/forms.py
from flask_wtf import Form
from wtforms.fields import Field
from wtforms import (SubmitField,
                     SelectField,
                     TextAreaField,
                     BooleanField,
                     FieldList, 
                     FormField,
                     HiddenField)
from wtforms.validators import Required, DataRequired, InputRequired
from wtforms.widgets import TextInput, ListWidget

class TagListField(Field):
    '''
    _value() is called by the TextInputWidget to provide the 
    value that is displayed in the form.
     
     process_formdata() processes incoming formdata back into a list of tags.
     '''
    
    widget = TextInput()

    def _value(self):
        if self.data:
            return ', '.join(self.data)
        else:
            return ''

    def process_formdata(self, valuelist):
        if valuelist:
            self.data = [x.strip() for x in valuelist[0].split(',')]
        else:
            self.data = []


class OptionForm(Form):
    option = TextAreaField('option')
    check_option = BooleanField()


class UserTagsForm(Form):
    tags = TagListField('Topic(s)', validators=[Required()])
    submit = SubmitField('Add')


class PostQuestionForm(Form):
    body = TextAreaField('Question?', validators=[Required()])
    description = TextAreaField('Description')

    tags = TagListField('Topic(s)', validators=[InputRequired()])

    option1 = TextAreaField('Option 1', validators=[Required()])
    check_option1 = BooleanField()
    
    option2 = TextAreaField('Option 2', validators=[Required()])
    check_option2 = BooleanField('check2')
    
    option3 = TextAreaField('Option 3')
    check_option3 = BooleanField('check3')
    
    option4 = TextAreaField('Option 4')
    check_option4 = BooleanField('check4')
    
    submit = SubmitField('Submit')


class EditQuestionForm(PostQuestionForm):
    option1_id = HiddenField('option1_id')
    option2_id = HiddenField('option2_id')
    option3_id = HiddenField('option3_id')
    option4_id = HiddenField('option4_id')


class SolutionForm(Form):
    body = TextAreaField('Solution', validators=[Required()])
    submit = SubmitField('Post')

app/question/__init__.py
from flask import Blueprint

question = Blueprint('question',__name__)

from . import views

app/question/views.py
from datetime import datetime, timedelta

from flask import render_template, flash, url_for
from flask import request, redirect, jsonify, current_app
from flask_login import current_user, login_required

from sqlalchemy.exc import SQLAlchemyError
from . import question
from .. import db
from ..models import (User,
                      Question, 
                      Option, 
                      Tag, 
                      SolvedQuestionsAssoc as SQ,
                      Solution,
                      ReportQuestionAssoc as RQ)
from .forms import (
                    PostQuestionForm, 
                    UserTagsForm, 
                    EditQuestionForm,
                    SolutionForm)
from ..utilities import add_to_db, bad_request, add_to_db_ajax, print_debug, dual_response


'''Helper Functions'''
def get_options(form):
    options = []
    is_all_false = True

    for fieldname, value in form.data.items():
        if fieldname.startswith('option'):
            if value:
                is_right = form.data.get('check_'+fieldname)
                option = Option(body=value)
                option.is_right = is_right
                
                if is_right:
                    is_all_false = False
                
                options.append(option)

    return None if is_all_false else options

def associate_tags(form):
    tags = []
    for tagname in form.tags.data:
        tag = Tag.query.filter_by(tagname=tagname).first()
        if not tag:
            tag = Tag(tagname=tagname)
        tags.append(tag)
        
    return None if tags == [] else tags


@question.route('/post-question', methods=['GET','POST'])
@login_required
def post_question():
    form = PostQuestionForm(request.form)

    if form.validate_on_submit():

        options = get_options(form)
        
        # options will be None if at least one option is not chosen
        if not options:
            flash('At least one option should be chosen as correct.', 'info')
            return redirect(url_for('.post_question'))

        tags = associate_tags(form)
        if len(tags) > 5:
            return dual_response('More than 5 tags are not allowed.')
        
        if not tags:
            flash('At least one tag is required.')
            return redirect(url_for('.post_question'))

        ques = Question(body=form.body.data,
                            description=form.description.data,
                            user=current_user,
                            options=options,
                            tags=associate_tags(form))
        try:
            db.session.add(ques)
            db.session.commit()
            flash('Question has been posted successfully.','success')
            return redirect(url_for('.questions', id=ques.id))
        except SQLAlchemyError:
            db.session.rollback()
            flash('There was a problem posting the question.', 'danger')
            return redirect(url_for('.post_question'))

    return render_template('question/post-question.html', form=form)


@question.route('/edit-question/<int:id>', methods=['GET','POST'])
@login_required
def edit_question(id):
    ques = Question.query.get_or_404(id)

    if current_user != ques.user:
        flash('You are not authorized to edit this question.', 'info')
        return redirect(url_for('.question', id=ques.id))

    form = EditQuestionForm()
    
    option_name = [
                    'option1',
                    'option2',
                    'option3',
                    'option4'
                    ]

    if form.validate_on_submit():
        
        ques.body = form.body.data
        ques.description = form.description.data
        ques.tags = associate_tags(form)

        is_all_false = True
        options = []
        for name in option_name:
            value = form.data.get(name)
            opt_id = form.data.get(name+'_id')
            is_right = form.data.get('check_'+name)
            option = Option.query.get(opt_id)

            if value:
                # Check to see whther there is atleast one right option
                if is_right:
                    is_all_false = False

                # If option is None, means a new option is being added
                if not option:
                    ques.options.append(Option(body=value,
                                               is_right=is_right)
                                            ) 
                    continue

                # A new value has been obtained. Edit the option.   
                # if the option is part of said question.
                if option in ques.options:
                    option.body = value
                    option.is_right = is_right
                else:
                    flash('Option being edited is not part of the question.','info')
                    return redirect(url_for('main.home'))

                options.append(option)

        if is_all_false:
            # if all the options are false, don't commit.
            flash('At least one option should be chosen as correct','info')
            return redirect(url_for('.edit_question', id=ques.id))
        else:
            db.session.add_all(options)

        try:
            db.session.add(ques)
            db.session.commit()
            flash('Question updated successfully.', 'success')
            return redirect(url_for('.questions', id=ques.id))
        except SQLAlchemyError, e:
            db.session.rollback()
            flash('There was a problem updating the question.', 'danger')
            return redirect(url_for('.edit_question', id=ques.id))
    
    # Fill the form if the form is just displayed
    form.body.data = ques.body
    form.description.data = ques.description

    options = ques.options
    if options:
        try:
            if options[0]:
                form.option1_id.data = options[0].id
                form.option1.data = options[0].body
                form.check_option1.data = options[0].is_right
            if options[1]:
                form.option2_id.data = options[1].id
                form.option2.data, form.check_option2.data = options[1].body, options[1].is_right
            if options[2]:
                form.option3_id.data = options[2].id
                form.option3.data, form.check_option3.data = options[2].body, options[2].is_right
            if options[3]:
                form.option4_id.data = options[3].id
                form.option4.data, form.check_option4.data = options[3].body, options[3].is_right
        except IndexError:
            pass
    
    """Build tag list for the form."""
    tags = []
    for tag in ques.tags:
        tags.append(tag.tagname)

    form.tags.data = tags

    return render_template('question/edit-question.html', form=form)


@question.route('/question/<int:id>')
@login_required
def questions(id):
    ques = Question.query.get(id)
    sol_form = SolutionForm()

    return render_template('question/question.html', 
                            ques=ques,
                            sol_form=sol_form)


@question.route('/get-tags', methods=['GET'])
@login_required
def get_tags():
    query = request.args.get('query')
    tags = Tag.query.filter(Tag.tagname.like('%{}%'.format(query)))
    
    result = {}
    for i, tag in enumerate(tags):
        result[i]=tag.tagname
    return jsonify(result)


@question.route('/check-answer', methods=['POST'])
@login_required
def check_answer():
    ques_id = request.form.get('question-id', 0, type=int)
    option_selected = request.form.getlist('opt')
    
    if not option_selected:
        return bad_request('Choose atleast one Option', 406)

    ques = Question.query.get_or_404(ques_id)

    result = {}
    is_solved = False
    for option_id in option_selected:
        option = Option.query.get_or_404(int(option_id))
        if option.is_right:
            result[str(option.id)]=True
            is_solved = True
        else:
            result[str(option.id)]=False
            is_solved = False
            break

    sq = SQ.query.filter_by(question=ques, user=current_user)\
                 .one_or_none()
    if not sq:
        sq = SQ(question=ques) # So that it complies with proxy
        sq.user = current_user
    sq.attempted += 1

    if is_solved:
        sq.solved = is_solved
        sq.is_set_unsolved = False
        current_user.update_streak()
    
    add_to_db_ajax(sq, 'Check-Answer: Operation Error while writing to DB')

    return jsonify(result)


@question.route('/tags')
@login_required
def tags():

    popular_tags = Tag.popular_tags()

    return render_template('popular_tags.html', popular_tags=popular_tags)


@question.route('/get-questions')
@login_required
def get_questions():
    # This solution form is needed since _questions.html contains the form.
    sol_form = SolutionForm()

    result = {}
    ques_id = request.args.get('question_id', 0, type=int)

    # if a particular question is given, then return only that
    # question. 

    if ques_id:
        ques = Question.query.get(ques_id)
        if ques:
            result[str(ques.id)] = render_template('question/_question.html',
                                                    ques=ques,
                                                    sol_form=sol_form)
        else:
            return bad_request('The given question does not exist.')
    else:
        if current_user.get_relevant_question():
            for ques in current_user.get_relevant_question():
                result[str(ques.id)] = render_template('question/_question.html',
                                                    ques=ques,
                                                    sol_form=sol_form)
        else:
            return bad_request('No more questions. Add More topics.')
    
    return jsonify(result)


@question.route('/post-solution', methods=['POST'])
@login_required
def post_solution():
    form = SolutionForm()

    if form.validate_on_submit():

app/templates/question/_modify_questions.html
{% import "_macros.html" as macros %}

	<div class="col-md-10 col-md-offset-1">
		<form id="modify-ques-form" method="POST">
			{{form.hidden_tag()}}

			<div class="row">
				<div class="col-md-5">
					{{macros.render_field(form.body, class='form-control', rows=5, required='required')}}
				</div>

				<div class="col-md-5 col-md-offset-1">
					<h5> Question </h5>
					<div class="questions">
						<p id="MathQues" class="placeholder-text">Question Preview</p>
					</div>
				</div>
			</div>
			<div class="options row">
				<div class="col-md-5">
					{{macros.render_field(form.option1, class='form-control', rows=1, required='required')}}

					{% if form.option1_id %}
						{{form.option1_id()}}
					{% endif %}
				</div>

				<div class="col-md-1">
					<div class="custom-checkbox">
						{{form.check_option1}}
						<label for="check_option1"></label>
					</div>
				</div>	

				<div class="col-md-5">
					{{macros.render_field(form.option2, class='form-control', required='required')}}

					{% if form.option2_id %}
						{{form.option2_id()}}
					{% endif %}
				</div>

				<div class="col-md-1">
					<div class="custom-checkbox">
						{{form.check_option2}}
						<label for="check_option2"></label>
					</div>
				</div>

				<div class="col-md-5">
					<p id="option_preview_1">Preview</p>
				</div>

				<div class="col-md-5 col-md-offset-1">
					<p id="option_preview_2">Preview</p>
				</div>

				<div class="col-md-5">
					{{macros.render_field(form.option3, class='form-control')}}

					{% if form.option3_id %}
						{{form.option3_id()}}
					{% endif %}
				</div>

				<div class="col-md-1">
					<div class="custom-checkbox">
						{{form.check_option3}}
						<label for="check_option3"></label>
					</div>
				</div>

				<div class="col-md-5">
					{{macros.render_field(form.option4, class='form-control')}}

					{% if form.option4_id %}
						{{form.option4_id()}}
					{% endif %}
				</div>

				<div class="col-md-1">
					<div class="custom-checkbox">
						{{form.check_option4}}
						<label for="check_option4"></label>
					</div>
				</div>

				<div class="col-md-5">
					<p id="option_preview_3">Preview</p>
				</div>

				<div class="col-md-5 col-md-offset-1">
					<p id="option_preview_4">Preview</p>
				</div>				
			</div>

			<div class="row">
				<div class="col-md-5">
					<ul>
						<li>Please provide meaningful descriptions such as the year and the paper in which this question appeared.</li>
					</ul>
					{{macros.render_field(form.description, class='form-control', rows=1)}}
				</div>

				<div class="col-md-5 col-md-offset-1">
					<h5> Description </h5>
					<div>
					<p id="desc-preview">Description Preview</p>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<ul>
						<li>Please see above conventions regarding <code>Tags</code></li>
						<li><p><code>Tags</code> are separated by <kbd>,</kbd> (comma)</p></li>
						<li>A maximum of <b>5</b> tags are permissable for a question.</li>
						<li>Please mention the name of <b>Entrance Exams</b> apart from the subjects if the question is aimed at preparation of aforementioned exams.
							<ul>
								<li><code>GATE</code></li>
								<li><code>AIPMT</code></li>
								<li><code>IIT-JEE</code></li>
							</ul>
						</li>
					</ul>
					
					{{macros.render_field(form.tags, class='form-control')}}
				</div>
			</div>

			<div>
				<div class="col-md-4 col-md-offset-4">
					{{form.submit(class='btn btn-block btn-primary', value='Post Question')}}
				</div>
			</div>
		</form>
	</div>

app/templates/question/_question.html
{% if not macros %}
	{% import "_macros.html" as macros with context %}
{% endif %}

{% if ques %}

		<!-- This is the question accessories -->
		<div class="row">
			<div class="col-md-1 accessories">
				<div class="btn-group-vertical">

					{{macros.upvote(current_user, ques)}}

					<h4 class="upvote-count text-center">{{ques.votes}}</h4>
					
					{{macros.downvote(current_user, ques)}}

					{{macros.favourite(current_user, ques)}}

					{% if current_user.id == ques.author_id %}
					<a href="{{url_for('question.edit_question', id=ques.id)}}" id="edit" class="btn btn-info">
						<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
					</a>
					{% endif %}

					{% if current_user.has_solved(ques) %}
					<button data-id="{{ques.id}}" class="unsolve-btn btn btn-success">
						<span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
					</button>
					{% endif %}


					<button id="report-question" data-count="{{ques.reported_wrong_ques}}" class="btn {% if current_user.has_reported(ques) %}btn-success{% else %}btn-default{%endif%}">
						<span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
					</button>

				</div>
			</div>

			<div class="col-md-11">
				<h5>Tags</h5>
				{% for tag in ques.tags %}
						<a class="btn {% if tag.has_user(current_user) %}btn-success{%else%}btn-info{%endif%} btn-xs" href="{{url_for('main.tags', tagname=tag.tagname)}}"><strong>{{tag.tagname}}</strong></a>
				{% endfor %}
			</div>
			
			<div class="col-md-11">	

				<div class="difficulty pull-right" {% if current_user.setting.hide_difficulty %} style="display: none" {% endif %}>
					<p>Solved {{ques.difficulty[1]}} times</p>
					<p>Attempted {{ques.difficulty[0]}} times</p> 
				</div>

				<h5>Question</h5>
				{%- if ques.reported_by.count() > 3 %}
				<div class="alert alert-warning alert-dismissible" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				  <strong>This question has been reprted {{ques.reported_by.count()}} time(s). Please verify the answer yourself.</strong> 
				</div>
				{% endif -%}
				<div>
					<p id="question-body" class="lead">{{ques.body}}</p>
				</div>
			</div>

			<div class="col-md-11">
				<form class="option-form">
					<input name="question-id" type="hidden" value="{{ques.id}}">
					
					
					<h5>Options</h5>
					
					<div class="hide-option-layer">
						
						<button id="show-options-btn" class=
						"btn btn-primary">Show Options</button>

					</div>
					{% set options = ques.options %}
					{% for option in options %}
						{% if option.body %}
							<div class="options">
								<div class="btn btn-default btn-block">
									{{option.body}}
								</div>
								<input type="hidden" value="{{option.id}}">
							</div>
						{% endif %}
					{% endfor %}


					<div class="row">

						<div class="ques-controls col-md-1">
							<div class="dropdown">
								<button id="ques-control" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<span class="caret"></span>
								</button>

								<ul class="dropdown-menu">
									<li><a href="{{url_for('question.questions', id=ques.id)}}"><span class="glyphicon glyphicon-paperclip"></span> Permalink</a></li>
								</ul>
							</div>

						</div>
						<div class="posted-on col-md-3">
							<span>
							Posted on <br/> {{ques.timestamp|time}}
							</span>
						</div>
						
						<div class="col-md-4">
							<div class="btn-group" role="group">
								<button id="submit-options" class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-send"></span> Check</button>
								<button id="skip-question-btn" type="button" class="btn btn-danger"><span class="glyphicon glyphicon-new-window"></span><strong>Skip</strong></button>
							</div>
						</div>
						
						{{macros.user_box(ques.user, class="home-user-box col-md-4 pull-right")}}

					</div>
				</form>
			</div>


			<div class="row">
				<div class="col-md-12">
					<hr>
				</div>
			</div>
			
			<div class="col-md-12">

					{% include "question/_tabs.html" %}
			</div>

		</div>



		
{% else %}
	{% if current_user.associated_tags.count() == 0 %}
	<br/>
	<br/>	
	<h5>Please choose at least one topic to populate the questions.</h5>
	<strong style="font-size: 20px;">Here is a quick walkthrough :-</strong>
	<ul style="font-size: 20px;">
		<li>You can <a href="{{url_for('question.tags')}}" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> <strong>Find Topics</strong></a> here.</li>
		<li>You can add <code>Topic(s)</code> - <br>
				<img class="" src="{{url_for('static', filename='sample1.jpg')}}" alt="Tutorial Image">
				<img src="{{url_for('static', filename='sample2.jpg')}}" alt="Tutorial Image">
		</li>
		<li>You can <a class="btn btn-info" href="{{url_for('question.post_question')}}"><strong><span class="glyphicon glyphicon-pencil"></span> Post Question</strong></a> in <b>Multiple Choice Format.</b></li>
		<li>You can use keys <kbd>1</kbd>, <kbd>2</kbd>, <kbd>3</kbd> or <kbd>4</kbd> to select options.</li>
		<li>You can answer other questions.</li>
		<li>Every correct answer will fetch you points.</li>
		<li>The streak counts the number of days that you have successfully solved questions</li>
		<li>The streak will be updated everyday when you successfully solve a question that day.</li>
	</ul>

	<img class="img-rounded center-block" width="350px" src="{{url_for('static', filename='ph.jpg')}}" />
	{% else %}
		<br/>
		<br/>

		<h5>You have exhausted all the questions</h5>
		<strong style="font-size: 20px;">You can post your own questions <a href="{{url_for('question.post_question')}}">here</a>. </strong>
	{% endif %}
{% endif %}

app/templates/question/_tabs.html
{% from "_macros.html" import user_box with context %}
<div>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#desc" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-comment"></span> Description</a>
        </li>

        <li role="presentation" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-blackboard"></span>Solutions <span class="badge">{{ques.solutions.count()}}</span><span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="#view-solutions" role="tab" data-toggle="tab">View Solutions</a>
                </li>
                <li><a href="#post-solution" role="tab" data-toggle="tab">Post Solutions</a>
                </li>
            </ul>
        </li>
    </ul>
    
    <div class="tab-content">

        <div role="tabpanel" class="tab-pane fade in active" id="desc">
            {% if ques.description %}
                <p>{{ques.description}}</p>
            {% else %}
                <h5>No description available</h5>
            {% endif %}
        </div>
        
        <div role="tabpanel" class="tab-pane fade in" id="view-solutions">
            
               {% include "_solutions.html" %}
            
        </div>

        <div role="tabpanel" class="tab-pane fade" id="post-solution">
            {% set sol = ques.solution_by_user(current_user)%} 
            
            {% if sol %}


            <div class="solution row">
                
                <div class="panel panel-info">

                    <div class="panel-heading">
                        You have already posted to solution to this question.
                    </div>
                    
                    <div id="to-edit" class="panel-body">{{sol.body}}</div>

                    <div class="panel-footer">
                        
                        <div class="row">
                            <div class="col-md-5">
                            {% if sol.user == current_user %}
                                <button id="edit-sol" data-id="{{sol.id}}" class="downvote-sol btn btn-info"><span class="glyphicon glyphicon-edit"></span> Edit</button>

                                <form class="inline" method="post" action="/delete-solution">
                                    <input type="hidden" name="sol-id" value="{{sol.id}}">
                                    <input type="submit" class="btn btn-danger" value="Delete">
                                </form>
                                
                            {% endif %}
                            </div>

                            {{user_box(sol.user, class="pull-right")}}
                        </div>
                        
                        
                    </div>

                </div>
            </div>
            {% endif %}
            
            {% if sol %}
                <form id="solution-form" action="post" style="display: none">
                    <input type="hidden" name="sol_id" value="{{sol.id}}">
            {% else %}
                <form id="solution-form" action="post">
            {% endif %}
                    {{sol_form.hidden_tag()}} 

                    {{macros.render_field(sol_form.body, class='form-control', required='required')}} 

                    <div>
                        <h5>Preview</h5>
                        <div>
                            <p id="sol-preview">Your Solution</p>
                        </div>
                    </div>

                    {{sol_form.submit(class='btn btn-primary')}}
                </form>

            
        </div>
    </div>
</div>

app/templates/question/edit-question.html
{% extends "base.html" %}

{% block title %}Edit Question{%endblock%}

{% block content%}
	{% include "question/_modify_questions.html" %}
{% endblock %}

app/templates/question/post-question.html
{% extends "base.html" %}

{% block title %}Post Question{% endblock %}
{% block content%}
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="help-info">
				<p class="lead">Post a Question!</p>
				<p>Here you can post your own questions. <b>Please follow the standard conventions described here.</b></p>
				<strong>Standard Conventions: </strong>
				<ul>
					<li>Please make sure that the question is unabmiguous, complete and correct.</li>
					<li><strong>For Math content:</strong> The <code>Question</code> field and the <code>Options</code> field support MathJax. For a quick reference and examples <a href="http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference">click</a> here.</li>
					<li>Only <strong>two</strong> options are necessary for a questions.</li>
					<li><b>More than one option can be correct.</b></li>
					<li><code>Description</code> is not necessary, however, it becomes easier for users to know additional information about the question. Descriptions can include:-</li>
						<ul>
							<li>The original author's name and/or year.</li>
							<li>The exam(s) in which the question appeared.</li>
							<li>Trivia etc.</li>
						</ul>
					<li>For maximum visibilty, choose the <code>Tags</code> carefully. The <code>Tags</code> are separated by a <code>,</code> (comma).</li>
					<li> <b>There can be a maximum of 5 tags per question.</b> The recommended number is <b>3</b>.</li>
					<li>Follow a heirarchy such as <b>Subject</b>,<b>Sub-field</b>, <b>Topic</b>, <b>Sub-topic</b> ... whenever applicable. Some examples are 
						<ul>
							<li>Computer, Compilers, LR Parsers</li>
							<li>Physics, Motion, Newton's Laws</li>
							<li>Math, Statistics, Regression</li>
						</ul>
					</li>

				</ul>
			
			</div>
		</div>
		{% include "question/_modify_questions.html" %}
	</div>
	
{% endblock %}